version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-patient-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1a574vga7off5"
s3_prefix = "demo-patient-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
